### ISSUE TITLE
Consider renaming `gem verify` to something more focused

### ISSUE THREAD

**Issue by rochlefebvre** [Shopify/ruby-sigstore#35]
`gem verify` feels overly broad as a command designed to look up gem signatures and validate them when present. `verify` makes me think along the lines of `gem check`: something about the integrity of the file itself.

Should we rename it into something that calls out signatures? There currently exists a single two-word command: `gem generate_index`.  We could introduce the second!

Suggestions (but maybe there's something even better)
- verify_signatures
- verify_signature
- check_signature

The command name should be kept in sync with the `gem install` option we're introducing in #34.  I prefer a plural form since a particular gem digest can be signed by many individuals.

**Comment by doodzik** [comment]
I wonder if it would make more sense to remove the dedicated commands altogether. I'm thinking of replacing them with cli options for the `gem install` and `gem build ` commands because the verification and signing logic is closely related to them.

It would definitely make our code a bit simpler as well, because we don't have to maintain that many implementations.

**Comment by doodzik** [comment]
I've been thinking some more about it after working triggering the gem verification through an environment variable #50. I'm wondering if it would be better if we were to use a `--security-policy` flag for the `install` and `build` command rather than a `sign` or `verify` flag/command.

That way we can provide a flexible interface for different strategies to gem installation and building process. There is also some [prior art in the rubygems repo where a similar system has been used](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/security/policies.rb).

**Comment by rochlefebvre** [comment]
Snapshot of a discussion we had on Slack on how to name our various commands and command options:

@rochlefebvre
Hi team!

I come seeking counsel :) Our sigstore prototype currently introduces four new actions:
1. `gem sign the_gem`
2. `gem verify the_gem`
3. `gem build --sign the_gem`
4. `gem install --verify the_gem`

Recall how the rubygems client usually follows this pattern: `gem <command> --option1 --option2 argument(s)`

So we're looking at two new commands, and two new options for the existing `build` and `install` commands.


I'm not a big fan the naming for number 2, `gem verify`.  IMO, _verify_ is too vague and too broad. We're not checking the integrity of a gem (e.g. checksums, files, spec, structure). We're checking some optional signatures which exist outside of the gem archive.

In https://github.com/Shopify/ruby-sigstore/issues/35 and https://github.com/Shopify/ruby-sigstore/pull/49, I proposed the following changes:

1. `gem sign the_gem`
2. **`gem verify_signatures the_gem`**
3. `gem build --sign the_gem`
4. **`gem install --verify-signatures the_gem`**

_Signatures_ is plural because a gem can be signed 0 or more times.  As I mentioned in the issue, two-word gem commands are rare, but there is at least one already. Note the consistency between actions 2 and 4, which I like.


Yesterday, Frederik had a good suggestion: have only one signing command:
1. **`gem signatures --sign the_gem`**
2. **`gem signatures --verify the_gem`**
3. `gem build --sign the_gem`
4. `gem install --verify-signatures the_gem`

Having a single command nicely groups the plugin's core functionality, which is common in the `gem` client's command syntax. `signatures` feels a tiny bit wonky to my ears.  I still prefer it to these ones, personally: `gem sign`, `gem sig`, or `gem sigs`.

We also cannot forget the 4th form: if possible, it should feel unambiguously related to action 2.

## Decisions
- Go with a single `signatures` command with `--sign` and `--verify` options.
- In the absence of options, `--verify` is the default behaviour.
- Support `--no-sign` and `--no-verify` forms as well.
- Action 4 will become `gem install --signing-policy`, which implies verifying gems at some default policy level.  The option can also accept indentifiers for policy levels, like rubygems' own `--trust-policy[=X]` currently does.
